- id: python-check-version
  name: python-check-version
  description: Check for version consistency between package, git tag, latest build, and changelog.
  entry: "gadzooks check-version"
  language: python
  args: []

- id: python-loc-summarize
  name: python-loc-summarize
  description: Display some LOC (lines of code) metrics for Python code via radon library.
  entry: "gadzooks loc-summarize"
  language: python
  args: ["**/*.py"]
