- id: build-docs
  name: build-docs
  description: Build project documentation.
  entry: "gadzooks build-docs"
  language: python
  args: []

- id: check-format
  name: check-format
  description: Check formatting of Python code using an installed code formatter.
  entry: "gadzooks check-format"
  language: python
  args: ["."]

- id: check-version
  name: check-version
  description: Check for version consistency between package, git tag, latest build, and changelog.
  entry: "gadzooks check-version"
  language: python
  args: []

- id: loc-summarize
  name: loc-summarize
  description: Display some LOC (lines of code) metrics for Python code via radon library.
  entry: "gadzooks loc-summarize"
  language: python
  args: ["."]
