- id: check-version
  name: check-version
  description: Check for version consistency between package, git tag, latest build, and changelog.
  entry: "gadzooks check-version"
  language: python
  args: []

- id: loc-summarize
  name: loc-summarize
  description: Display some LOC (lines of code) metrics for Python code via radon library.
  entry: "gadzooks loc-summarize"
  language: python
  args: ["."]
